export const lawyers = [
    { id: 1, name: "John Doe", specialization: "Criminal Law", image: "/lawyer1.jpg" },
    { id: 2, name: "Jane Smith", specialization: "Family Law", image: "/lawyer2.jpg" },
    { id: 3, name: "David Johnson", specialization: "Corporate Law", image: "/lawyer3.jpg" },
    { id: 4, name: "Alice Brown", specialization: "Tax Law", image: "/lawyer4.jpg" },
    { id: 5, name: "Michael White", specialization: "Real Estate Law", image: "/lawyer5.jpg" },
    { id: 6, name: "Sarah Miller", specialization: "Criminal Law", image: "/lawyer6.jpg" },
    { id: 7, name: "Robert Wilson", specialization: "Family Law", image: "/lawyer7.jpg" },
    { id: 8, name: "Emily Davis", specialization: "Corporate Law", image: "/lawyer8.jpg" },
    { id: 9, name: "William Anderson", specialization: "Tax Law", image: "/lawyer9.jpg" },
    { id: 10, name: "Jessica Thompson", specialization: "Real Estate Law", image: "/lawyer10.jpg" },
    { id: 11, name: "James Martinez", specialization: "General Law", image: "/lawyer11.jpg" },
    { id: 12, name: "Laura Hernandez", specialization: "Family Law", image: "/lawyer12.jpg" },
    { id: 13, name: "Daniel Lopez", specialization: "Corporate Law", image: "/lawyer13.jpg" },
    { id: 14, name: "Sophia Gonzalez", specialization: "Tax Law", image: "/lawyer14.jpg" },
    { id: 15, name: "Chris Walker", specialization: "Intellectual Property Law", image: "/lawyer15.jpg" },
    { id: 16, name: "Anna Hall", specialization: "Immigration Law", image: "/lawyer16.jpg" },
    { id: 17, name: "Henry Young", specialization: "Employment Law", image: "/lawyer17.jpg" },
    { id: 18, name: "Victoria Scott", specialization: "Corporate Law", image: "/lawyer18.jpg" },
    { id: 19, name: "Benjamin Adams", specialization: "General Law", image: "/lawyer19.jpg" },
    { id: 20, name: "Olivia Carter", specialization: "Real Estate Law", image: "/lawyer20.jpg" },
    { id: 21, name: "Nathan Wright", specialization: "Criminal Law", image: "/lawyer21.jpg" },
    { id: 22, name: "Emma King", specialization: "Family Law", image: "/lawyer22.jpg" },
    { id: 23, name: "Samuel Allen", specialization: "Corporate Law", image: "/lawyer23.jpg" },
    { id: 24, name: "Grace Nelson", specialization: "Tax Law", image: "/lawyer24.jpg" },
    { id: 25, name: "Ethan Hill", specialization: "Intellectual Property Law", image: "/lawyer25.jpg" },
    { id: 26, name: "Mia Baker", specialization: "Immigration Law", image: "/lawyer26.jpg" },
    { id: 27, name: "Logan Green", specialization: "Employment Law", image: "/lawyer27.jpg" },
    { id: 28, name: "Abigail Hall", specialization: "Corporate Law", image: "/lawyer28.jpg" },
    { id: 29, name: "Alexander Lewis", specialization: "General Law", image: "/lawyer29.jpg" },
    { id: 30, name: "Sophia Roberts", specialization: "Real Estate Law", image: "/lawyer30.jpg" },
    { id: 31, name: "Matthew Clark", specialization: "Criminal Law", image: "/lawyer31.jpg" },
    { id: 32, name: "Isabella Rodriguez", specialization: "Family Law", image: "/lawyer32.jpg" },
    { id: 33, name: "Jack Torres", specialization: "Corporate Law", image: "/lawyer33.jpg" },
    { id: 34, name: "Charlotte Ramirez", specialization: "Tax Law", image: "/lawyer34.jpg" },
    { id: 35, name: "Andrew Scott", specialization: "General Law", image: "/lawyer35.jpg" },
    { id: 36, name: "Lucas Bennett", specialization: "Criminal Law", image: "/lawyer36.jpg" },
    { id: 37, name: "Madeline Reed", specialization: "Family Law", image: "/lawyer37.jpg" },
    { id: 38, name: "Mason Powell", specialization: "Real Estate Law", image: "/lawyer38.jpg" },
    { id: 39, name: "Eleanor Hughes", specialization: "Intellectual Property Law", image: "/lawyer39.jpg" },
    { id: 40, name: "Gabriel Patterson", specialization: "Employment Law", image: "/lawyer40.jpg" },
    { id: 41, name: "Scarlett Foster", specialization: "Immigration Law", image: "/lawyer41.jpg" },
    { id: 42, name: "Benjamin Wright", specialization: "General Law", image: "/lawyer42.jpg" },
    { id: 43, name: "Natalie Richardson", specialization: "Corporate Law", image: "/lawyer43.jpg" },
    { id: 44, name: "Jonathan Torres", specialization: "Criminal Law", image: "/lawyer44.jpg" },
    { id: 45, name: "Isla Murphy", specialization: "Family Law", image: "/lawyer45.jpg" },
    { id: 46, name: "Adam Carter", specialization: "Real Estate Law", image: "/lawyer46.jpg" },
    { id: 47, name: "Lily Brooks", specialization: "Intellectual Property Law", image: "/lawyer47.jpg" },
    { id: 48, name: "Oliver Evans", specialization: "Tax Law", image: "/lawyer48.jpg" },
    { id: 49, name: "Sophie Ramirez", specialization: "Immigration Law", image: "/lawyer49.jpg" },
    { id: 50, name: "Daniel Bennett", specialization: "General Law", image: "/lawyer50.jpg" },
  ];
  